### ISSUE TITLE
[iOS] add text on video

### ISSUE THREAD

**Issue by tkmct** [Takamichi-tsutsumi/react-native-media-editor#2]
## policy
Use AVMutable composition to create composition with video track.
Then create some text layer and put it on videoLayer.
Finally composite those layers together.

**Comment by srameshr** [comment]
Is this done?

**Comment by tkmct** [comment]
@srameshr Currently not under development.

**Comment by srameshr** [comment]
@Takamichi-tsutsumi Do you know any other react native packages, that does the same?

**Comment by tkmct** [comment]
@srameshr Sorry I don't. but it's not so hard to implement it by building NativeModules.
There're tons of blog posts how to do it in Objective-C. All you need to do is to implement the function in Objective-C and make it into NativeModules. And just call the function from React-Native code.

**Comment by srameshr** [comment]
I have never used Objective-C. Sorry!
